# Generated by Django 4.0.6 on 2022-07-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_member_project_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ManyToManyField(to='app.project'),
        ),
    ]
