# Generated by Django 4.0.6 on 2022-07-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_is_admin_user_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
